import type { User, WatchlistItem, RecommendationCard, PerformanceRecord } from './types';

export const mockUser: User = {
  name: '화영',
  timezone: 'Asia/Seoul',
  defaultRiskProfile: 'balanced',
  pushEnabled: true,
};

export const availableWatchlistItems: WatchlistItem[] = [
  { ticker: 'AAPL', name: 'Apple', kind: 'ticker' },
  { ticker: 'TSLA', name: 'Tesla', kind: 'ticker' },
  { ticker: 'NVDA', name: 'Nvidia', kind: 'ticker' },
  { ticker: 'MSFT', name: 'Microsoft', kind: 'ticker' },
  { ticker: 'AMZN', name: 'Amazon', kind: 'ticker' },
  { ticker: 'META', name: 'Meta', kind: 'ticker' },
  { ticker: 'TECH', name: 'Technology sector', kind: 'sector' },
  { ticker: 'HEALTH', name: 'Healthcare sector', kind: 'sector' },
  { ticker: 'CONSUMER', name: 'Consumer sector', kind: 'sector' },
];

export const defaultWatchlist: string[] = ['AAPL', 'TSLA', 'NVDA'];

export const watchlistItemByTicker = Object.fromEntries(
  availableWatchlistItems.map(item => [item.ticker, item])
);

// Balanced recommendations
const balancedRecommendations: RecommendationCard[] = [
  {
    id: 'nvda-balanced',
    ticker: 'NVDA',
    companyName: 'Nvidia',
    direction: 'BUY',
    entryRangeMin: 820,
    entryRangeMax: 835,
    targetRangeMin: 875,
    targetRangeMax: 895,
    exitPrice: 792,
    holdDays: 5,
    confidenceScore: 'balanced',
    actionLabel: '계획 매수',
    reasonLine: '데이터센터 수요와 최근 거래량 회복이 단기 추세 유지 가능성을 높입니다.',
  },
  {
    id: 'aapl-balanced',
    ticker: 'AAPL',
    companyName: 'Apple',
    direction: 'BUY',
    entryPrice: 168.40,
    targetPrice: 176.00,
    exitPrice: 162.80,
    holdDays: 4,
    confidenceScore: 'balanced',
    actionLabel: '분할 진입',
    reasonLine: '신제품 기대보다 자사주 매입과 방어적 수급이 단기 하방을 제한하고 있습니다.',
  },
  {
    id: 'tsla-balanced',
    ticker: 'TSLA',
    companyName: 'Tesla',
    direction: 'SELL',
    entryRangeMin: 151,
    entryRangeMax: 154,
    targetRangeMin: 141,
    targetRangeMax: 145,
    exitPrice: 159,
    holdDays: 3,
    confidenceScore: 'balanced',
    actionLabel: '반등 시 매도',
    reasonLine: '단기 반등 이후 거래량이 약해져 3영업일 내 되돌림 가능성이 있습니다.',
  },
  {
    id: 'tech-balanced',
    ticker: 'TECH',
    companyName: 'Technology sector',
    direction: 'BUY',
    entryRangeMin: 122,
    entryRangeMax: 125,
    targetRangeMin: 130,
    targetRangeMax: 134,
    exitPrice: 118,
    holdDays: 5,
    confidenceScore: 'balanced',
    actionLabel: '섹터 분할 진입',
    reasonLine: '대형 기술주의 실적 기대와 AI 인프라 수요가 섹터 전반의 단기 강세를 지지합니다.',
  },
  {
    id: 'health-balanced',
    ticker: 'HEALTH',
    companyName: 'Healthcare sector',
    direction: 'BUY',
    entryRangeMin: 88,
    entryRangeMax: 90,
    targetRangeMin: 94,
    targetRangeMax: 97,
    exitPrice: 85,
    holdDays: 6,
    confidenceScore: 'balanced',
    actionLabel: '방어 섹터 매수',
    reasonLine: '금리 변동성 구간에서 헬스케어의 방어적 수급이 상대 강도를 유지하고 있습니다.',
  },
  {
    id: 'consumer-balanced',
    ticker: 'CONSUMER',
    companyName: 'Consumer sector',
    direction: 'SELL',
    entryRangeMin: 74,
    entryRangeMax: 76,
    targetRangeMin: 69,
    targetRangeMax: 71,
    exitPrice: 79,
    holdDays: 4,
    confidenceScore: 'balanced',
    actionLabel: '반등 시 비중 축소',
    reasonLine: '소비 둔화 우려가 남아 있어 경기민감 소비 섹터는 단기 조정 가능성을 열어둬야 합니다.',
  },
];

// Aggressive recommendations
const aggressiveRecommendations: RecommendationCard[] = [
  {
    id: 'nvda-aggressive',
    ticker: 'NVDA',
    companyName: 'Nvidia',
    direction: 'BUY',
    entryRangeMin: 835,
    entryRangeMax: 845,
    targetRangeMin: 900,
    targetRangeMax: 925,
    exitPrice: 805,
    holdDays: 3,
    confidenceScore: 'aggressive',
    actionLabel: '빠른 진입',
    reasonLine: '데이터센터 수요와 최근 거래량 회복이 단기 추세 유지 가능성을 높입니다.',
  },
  {
    id: 'aapl-aggressive',
    ticker: 'AAPL',
    companyName: 'Apple',
    direction: 'BUY',
    entryPrice: 169.80,
    targetPrice: 179.50,
    exitPrice: 164.00,
    holdDays: 3,
    confidenceScore: 'aggressive',
    actionLabel: '공격 매수',
    reasonLine: '신제품 기대보다 자사주 매입과 방어적 수급이 단기 하방을 제한하고 있습니다.',
  },
  {
    id: 'tsla-aggressive',
    ticker: 'TSLA',
    companyName: 'Tesla',
    direction: 'SELL',
    entryRangeMin: 153,
    entryRangeMax: 156,
    targetRangeMin: 137,
    targetRangeMax: 142,
    exitPrice: 161,
    holdDays: 2,
    confidenceScore: 'aggressive',
    actionLabel: '단기 매도',
    reasonLine: '단기 반등 이후 거래량이 약해져 3영업일 내 되돌림 가능성이 있습니다.',
  },
  {
    id: 'tech-aggressive',
    ticker: 'TECH',
    companyName: 'Technology sector',
    direction: 'BUY',
    entryRangeMin: 124,
    entryRangeMax: 127,
    targetRangeMin: 134,
    targetRangeMax: 138,
    exitPrice: 119,
    holdDays: 3,
    confidenceScore: 'aggressive',
    actionLabel: '섹터 빠른 진입',
    reasonLine: 'AI 관련 대형주의 모멘텀이 강해 기술 섹터의 단기 추세 추종 구간으로 판단합니다.',
  },
  {
    id: 'health-aggressive',
    ticker: 'HEALTH',
    companyName: 'Healthcare sector',
    direction: 'BUY',
    entryRangeMin: 89,
    entryRangeMax: 91,
    targetRangeMin: 96,
    targetRangeMax: 99,
    exitPrice: 86,
    holdDays: 4,
    confidenceScore: 'aggressive',
    actionLabel: '돌파 추종',
    reasonLine: '헬스케어 대형주의 실적 발표 전 수급 유입이 이어져 단기 상방 여지가 있습니다.',
  },
  {
    id: 'consumer-aggressive',
    ticker: 'CONSUMER',
    companyName: 'Consumer sector',
    direction: 'SELL',
    entryRangeMin: 75,
    entryRangeMax: 77,
    targetRangeMin: 68,
    targetRangeMax: 70,
    exitPrice: 80,
    holdDays: 3,
    confidenceScore: 'aggressive',
    actionLabel: '약세 추종',
    reasonLine: '소비 섹터의 실적 가이던스 하향 가능성이 남아 있어 단기 하락 추세 대응이 유효합니다.',
  },
];

// Conservative recommendations
const conservativeRecommendations: RecommendationCard[] = [
  {
    id: 'nvda-conservative',
    ticker: 'NVDA',
    companyName: 'Nvidia',
    direction: 'BUY',
    entryRangeMin: 805,
    entryRangeMax: 818,
    targetRangeMin: 852,
    targetRangeMax: 868,
    exitPrice: 785,
    holdDays: 7,
    confidenceScore: 'conservative',
    actionLabel: '눌림 확인',
    reasonLine: '데이터센터 수요와 최근 거래량 회복이 단기 추세 유지 가능성을 높입니다.',
  },
  {
    id: 'aapl-conservative',
    ticker: 'AAPL',
    companyName: 'Apple',
    direction: 'BUY',
    entryPrice: 166.20,
    targetPrice: 173.20,
    exitPrice: 161.50,
    holdDays: 6,
    confidenceScore: 'conservative',
    actionLabel: '안정 진입',
    reasonLine: '신제품 기대보다 자사주 매입과 방어적 수급이 단기 하방을 제한하고 있습니다.',
  },
  {
    id: 'tsla-conservative',
    ticker: 'TSLA',
    companyName: 'Tesla',
    direction: 'SELL',
    entryRangeMin: 148,
    entryRangeMax: 151,
    targetRangeMin: 143,
    targetRangeMax: 146,
    exitPrice: 156,
    holdDays: 5,
    confidenceScore: 'conservative',
    actionLabel: '보수 관찰',
    reasonLine: '단기 반등 이후 거래량이 약해져 3영업일 내 되돌림 가능성이 있습니다.',
  },
  {
    id: 'tech-conservative',
    ticker: 'TECH',
    companyName: 'Technology sector',
    direction: 'BUY',
    entryRangeMin: 119,
    entryRangeMax: 122,
    targetRangeMin: 127,
    targetRangeMax: 131,
    exitPrice: 116,
    holdDays: 7,
    confidenceScore: 'conservative',
    actionLabel: '눌림 확인 후 진입',
    reasonLine: '기술 섹터는 변동성이 크지만 실적 시즌 기대가 있어 조정 시 분할 접근이 유리합니다.',
  },
  {
    id: 'health-conservative',
    ticker: 'HEALTH',
    companyName: 'Healthcare sector',
    direction: 'BUY',
    entryRangeMin: 87,
    entryRangeMax: 88,
    targetRangeMin: 92,
    targetRangeMax: 95,
    exitPrice: 84,
    holdDays: 7,
    confidenceScore: 'conservative',
    actionLabel: '방어적 분할 진입',
    reasonLine: '헬스케어는 방어적 특성상 변동성 구간에서도 상대적으로 안정적인 흐름을 기대할 수 있습니다.',
  },
  {
    id: 'consumer-conservative',
    ticker: 'CONSUMER',
    companyName: 'Consumer sector',
    direction: 'SELL',
    entryRangeMin: 73,
    entryRangeMax: 75,
    targetRangeMin: 70,
    targetRangeMax: 72,
    exitPrice: 78,
    holdDays: 5,
    confidenceScore: 'conservative',
    actionLabel: '신중한 비중 축소',
    reasonLine: '경기 둔화 신호가 이어지는 동안 소비 섹터는 보수적으로 대응하는 편이 적절합니다.',
  },
];

export const recommendationsByRisk = {
  conservative: conservativeRecommendations,
  balanced: balancedRecommendations,
  aggressive: aggressiveRecommendations,
};

export const performanceRecords: PerformanceRecord[] = [
  {
    ticker: 'TECH',
    predictedDirection: 'BUY',
    realizedReturn: '+3.9%',
    hitFlag: 'success',
    evaluationWindowDays: 5,
    evaluatedAt: '2026-04-20',
  },
  {
    ticker: 'NVDA',
    predictedDirection: 'BUY',
    realizedReturn: '+4.8%',
    hitFlag: 'success',
    evaluationWindowDays: 5,
    evaluatedAt: '2026-04-19',
  },
  {
    ticker: 'AAPL',
    predictedDirection: 'BUY',
    realizedReturn: '+2.1%',
    hitFlag: 'success',
    evaluationWindowDays: 4,
    evaluatedAt: '2026-04-18',
  },
  {
    ticker: 'TSLA',
    predictedDirection: 'SELL',
    realizedReturn: '-3.4%',
    hitFlag: 'success',
    evaluationWindowDays: 3,
    evaluatedAt: '2026-04-17',
  },
  {
    ticker: 'HEALTH',
    predictedDirection: 'BUY',
    realizedReturn: '+1.4%',
    hitFlag: 'success',
    evaluationWindowDays: 6,
    evaluatedAt: '2026-04-17',
  },
  {
    ticker: 'META',
    predictedDirection: 'BUY',
    realizedReturn: '-1.2%',
    hitFlag: 'fail',
    evaluationWindowDays: 5,
    evaluatedAt: '2026-04-16',
  },
  {
    ticker: 'MSFT',
    predictedDirection: 'BUY',
    realizedReturn: '+0.8%',
    hitFlag: 'success',
    evaluationWindowDays: 4,
    evaluatedAt: '2026-04-15',
  },
  {
    ticker: 'AMZN',
    predictedDirection: 'SELL',
    realizedReturn: '+1.6%',
    hitFlag: 'fail',
    evaluationWindowDays: 3,
    evaluatedAt: '2026-04-14',
  },
  {
    ticker: 'CONSUMER',
    predictedDirection: 'SELL',
    realizedReturn: '-1.1%',
    hitFlag: 'fail',
    evaluationWindowDays: 4,
    evaluatedAt: '2026-04-14',
  },
  {
    ticker: 'NVDA',
    predictedDirection: 'BUY',
    realizedReturn: '+6.2%',
    hitFlag: 'success',
    evaluationWindowDays: 5,
    evaluatedAt: '2026-04-13',
  },
  {
    ticker: 'AAPL',
    predictedDirection: 'SELL',
    realizedReturn: '-2.4%',
    hitFlag: 'success',
    evaluationWindowDays: 4,
    evaluatedAt: '2026-04-12',
  },
  {
    ticker: 'TSLA',
    predictedDirection: 'BUY',
    realizedReturn: '-0.5%',
    hitFlag: 'fail',
    evaluationWindowDays: 3,
    evaluatedAt: '2026-04-11',
  },
  {
    ticker: 'META',
    predictedDirection: 'BUY',
    realizedReturn: '+3.7%',
    hitFlag: 'success',
    evaluationWindowDays: 5,
    evaluatedAt: '2026-04-10',
  },
];
