import { getTodayRecommendations } from "@/lib/queries/getTodayRecommendations";

function Disclaimer() {
  return (
    <p className="mt-6 text-xs text-muted-foreground max-w-md text-center">
      This is not investment advice. Recommendations are generated by an AI
      model and may not reflect actual market conditions. Always do your own
      research before making trading decisions.
    </p>
  );
}

export default async function Home() {
  const result = await getTodayRecommendations();

  if (result.status === "no_call") {
    return (
      <main className="flex min-h-screen flex-col items-center justify-center bg-background text-foreground p-4">
        <h1 className="text-2xl font-medium mb-2">StockAlarm</h1>
        <p className="text-muted-foreground text-center max-w-sm">
          {result.reason}
        </p>
        <Disclaimer />
      </main>
    );
  }

  return (
    <main className="min-h-screen bg-background text-foreground p-4">
      <h1 className="text-2xl font-medium mb-6">Today&apos;s Recommendations</h1>

      <div className="space-y-4 max-w-lg mx-auto">
        {result.cards.map((card) => (
          <div
            key={card.id}
            className="rounded-lg border bg-card p-4 shadow-sm"
          >
            <div className="flex items-center justify-between mb-2">
              <span className="font-semibold text-lg">{card.ticker}</span>
              <span
                className={`text-sm font-medium px-2 py-0.5 rounded ${
                  card.direction === "BUY"
                    ? "bg-emerald-100 text-emerald-800"
                    : "bg-rose-100 text-rose-800"
                }`}
              >
                {card.direction}
              </span>
            </div>

            <div className="text-sm text-muted-foreground space-y-1">
              <p>
                Entry:{" "}
                {card.entryPrice != null
                  ? `$${card.entryPrice.toFixed(2)}`
                  : `$${card.entryRangeLow?.toFixed(2)} – $${card.entryRangeHigh?.toFixed(2)}`}
                {" | "}
                Target:{" "}
                {card.targetPrice != null
                  ? `$${card.targetPrice.toFixed(2)}`
                  : `$${card.targetRangeLow?.toFixed(2)} – $${card.targetRangeHigh?.toFixed(2)}`}
              </p>
              <p>Hold: {card.holdDays} business days</p>
              <p>
                Risk:{" "}
                <span className="capitalize">{card.confidenceScore}</span>
              </p>
              <p className="italic mt-2">{card.reasonLine}</p>
            </div>
          </div>
        ))}
      </div>

      <Disclaimer />
    </main>
  );
}
